apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pull-request
  namespace: tekton-builds
spec:
  params:
    - name: gitrevision
      value: $(body.pull_request.head.sha)
    - name: namespace
      value: tekton-builds
    - name: gitrepositoryurl
      value: https://github.com/$(body.repository.full_name)
    - name: projectname
      value: $(body.repository.name)
