apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-builds
spec:
  serviceAccountName: tekton-triggers
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: github-push
      interceptors:
        - ref:
            kind: ClusterInterceptor
            name: github
          params:
            - name: eventTypes
              value:
                - push
      template:
        ref: github-push-trigger-template
    - bindings:
        - kind: TriggerBinding
          ref: github-pull-request
      interceptors:
        - params:
            - name: eventTypes
              value:
                - pull_request
          ref:
            kind: ClusterInterceptor
            name: github
      template:
        ref: github-pull-request-trigger-template
