apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: vulnerability-scan
  namespace: tekton-builds
spec:
  params:
    - name: sbom-path
      description: Path to the sbom to scan
      type: string
    - name: output-format
      description: Vulnerability report format
      type: string
      default: cyclonedx-json
  steps:
    - name: vulnerability-scan
      args:
        - sbom:$(params.sbom-path)
        - --output=$(params.output-format)
        - --file=$(workspaces.workspace.path)/vulns
      image: anchore/grype:v0.79.6-debug
      workingDir: /tmp
  workspaces:
    - name: workspace
  # - mountPath: /config
  #   name: dockerconfig
  #   optional: true
