apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tektonic-pipeline-npm-pull-request.k8s.yaml
  - tektonic-pipeline-npm-push.k8s.yaml
  - tektonic-task-anchore-scan.k8s.yaml
  - tektonic-task-build-npm.k8s.yaml
  - tektonic-task-git-clone.k8s.yaml
  - tektonic-task-set-status-pending.k8s.yaml
  - tektonic-task-test-npm.k8s.yaml
  - tektonic-tekton-infra.k8s.yaml
