apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tektonic-npm-push
  namespace: tektonic-ci
spec:
  params:
    - name: project-name
      type: string
    - name: repo-full-name
      type: string
    - name: revision
      type: string
    - name: url
      type: string
    - name: ref
      type: string
  tasks:
    - name: set-status-pending
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: tektonic-set-status-pending
    - name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      taskRef:
        kind: Task
        name: tektonic-git-clone
      workspaces:
        - name: workspace
          workspace: workspace
    - name: test-npm
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - set-status-pending
      taskRef:
        kind: Task
        name: tektonic-test-npm
      workspaces:
        - name: workspace
          workspace: workspace
    - name: anchore-scan
      params:
        - name: ref
          value: $(params.ref)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - set-status-pending
      taskRef:
        kind: Task
        name: tektonic-anchore-scan
      workspaces:
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace
